### ISSUE TITLE
qemu-armv7 build in Dockerfile.

### ISSUE THREAD

**Issue by ControlCplusControlV** [MarijnStevens/ya-runtime-vm#3]
Nothing in particular, but I can make issues

**Comment by ControlCplusControlV** [comment]
Ok, so this is the issue relating to the qemu build dockerfile with a target for the binaries of armv7?

**Comment by MarijnStevens** [comment]
Not supported anymore. See [here](https://github.com/MarijnStevens/ya-runtime-vm/milestone/1)

**Comment by MarijnStevens** [comment]
T
